### ISSUE TITLE
First example in the tutorial doesn't compile

### ISSUE THREAD

**Issue by canndrew** [np/ling#36]
Dunno if this is the right place to file this issue, but anyway...

The tutorial opens with the following code example:

```
sum_int = proc(a : {?Int ^ 10}, r : !Int)
  new/alloc [itmp : !Int.?Int, tmp]
  ( send itmp 0.
    fwd(?Int)(itmp, r)
  | a{ai}
    slice (ai) 10 as i
      recv ai  (x : Int).
      recv tmp (y : Int).
      send tmp (x + y))
```

When I try to build this with a freshly cloned and built ling compiler it gives me an error:

```
While checking `sum_int`
  While checking `ai`
    Replication factors are not equivalent.
    Annotation:
      1
    Inferred:
      10
```

**Comment by np** [comment]
Thanks for your report. Yes the issue tracker is definitely the right place to report this or even ask questions about the language.

The tutorial is getting outdated. However while the syntax is evolving, I'm keeping backward compatibility when possible.

If your looking at a good/better example have a look at `fixtures/all/matmul_seq.ll` in the repo.
